name: Backup and Restore Workflow

on:
  push:
    branches:
      - main

jobs:
  backup_restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Backup and Restore Containers
        run: |
          docker-compose up -d
          sleep 10
          docker-compose logs
